### PR TITLE
Improve mobile header

### PR DESCRIPTION
**Pull request by ckt624**

### CODE REVIEW

**Comment by tslmy** [comment]
image
Still white-on-white.

**Review by tslmy — CHANGES_REQUESTED** [review]
Stil white-on-white.

**Comment by ckt624** [comment]
> Stil white-on-white.

Changed to black-on-white

**Comment by tslmy** [comment]
image

**Comment by ckt624** [comment]
> image

Fixed.

**Review by tslmy — APPROVED** [review]

**Pull request merged**
